name: Build and publish base image

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: office-linux-actions
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish the image
        run: |
          echo "${{ secrets.OFFICE_OS_TOKEN }}" | podman login --username JakubSzukala --password-stdin ghcr.io
          podman build -t ghcr.io/jakubszukala/office-os:latest .
          podman push ghcr.io/jakubszukala/office-os:latest

